### ISSUE TITLE
Set a pattern(s) for all file types

### ISSUE THREAD

**Issue by KabbAmine** [roxma/SimpleAutoComplPop#2]
First of all, thanks for your plugin. I'm a heavy user of neocomplete but I like testing other completion plugins and I really like the logic of SACP :smiley: 

Its quite redundant to define the same patterns for many file types, so it would be great to allow using `*` or something like that.

``` vim
" Define the patterns
autocmd FileType * call sacp#enableForThisBuffer({ "matches": [
    \     {'=~': '\v[a-zA-Z]{4}$'     , 'feedkeys': "\<C-x>\<C-n>"} ,
    \     {'=~': '\v(\~|\/)'                , 'feedkeys': "\<C-x>\<C-f>"} ,
    \ ]})

" Then enable sacp for all file types
let g:sacpDefaultFileTypesEnable['*'] = 1
```

Is something like that already implemented?

**Comment by roxma** [comment]
``` vim
autocmd FileType * call sacp#enableForThisBuffer({ "matches": [
    \     {'=~': '\v[a-zA-Z]{4}$'     , 'feedkeys': "\<C-x>\<C-n>"} ,
    \     {'=~': '\v(\~|\/)'                , 'feedkeys': "\<C-x>\<C-f>"} ,
    \ ]})
```

I believe this would be enough for your use case. There's no generous pattern for all file type, so I believe it's meaningless to choose a pattern for `let g:sacpDefaultFileTypesEnable['*'] = 1`

**Comment by KabbAmine** [comment]
Strangely, that didn't work the 1st time but now its ok, thanks again.
