### ISSUE TITLE
Match whole line

### ISSUE THREAD

**Issue by KabbAmine** [roxma/SimpleAutoComplPop#3]
In python, I would like to use omnicompletion this way:

``` python
# Example 1
import <HERE>

# Example 2
from <HERE> import <HERE>
```

Using this:

``` vim
{ '=~': '\v(import|from)\ ', 'feedkeys': "\<C-x>\<C-o>"},
```

It have omnicompletion:
- After `import` in the 1st example.
- After `from` but not after `import` in the 2nd example.

So how can I implement that? How can I define a pattern that will match the whole line?

**Comment by roxma** [comment]
Try `ignoreCompletionMode` option and append a `$` to the pattern to stop re-feeding `"\<C-x>\<C-o>"`.

``` vim
{ '=~': '\v(import|from)\ $', 'feedkeys': "\<C-x>\<C-o>", "ignoreCompletionMode":1},
```

**Comment by KabbAmine** [comment]
It works, thanks
