### ISSUE TITLE
Option not to overwrite existing completeopt

### ISSUE THREAD

**Issue by msjyoo** [roxma/SimpleAutoComplPop#5]
Hello,

I've already set a completeopt option on my .vimrc, there should be an option not to overwrite the already existing completeopt / not overwrite it at all if it is set.

Thanks, and really nice work! This is really useful.

**Comment by roxma** [comment]
Try add  the field `'completeopt':&l:completeopt` to the dictionary which is passed to `sacp#enableForThisBuffer`.

**Comment by msjyoo** [comment]
Yep, that's the method I used after looking through source :P
