### ISSUE TITLE
Plugin overrides <S-Tab>

### ISSUE THREAD

**Issue by msjyoo** [roxma/SimpleAutoComplPop#7]
Again, not desirable behaviour. What does that part in sacp.vim do anyway? I couldn't figure it out.

**Comment by roxma** [comment]
`<S-Tab>` is for selecting the previous item in the popup menu. This is how I use an IDE with auto-completion feature back in the days.

Checkout the latest version of SACP, add `let g:sacpDefaultKeyMapEnable = 0` into your vimrc if you need to custom your own key mapping.

EDIT:

Currently there're only three default key mappings by SACP

```
        inoremap <expr> <buffer> <silent> <TAB>  pumvisible()?"\<C-n>":"\<TAB>"
        inoremap <expr> <buffer> <silent> <S-TAB>  pumvisible()?"\<C-p>":"\<TAB>"
        inoremap <expr> <buffer> <silent> <CR>  pumvisible()?"\<C-y>":"\<CR>"
```
1. `<TAB>`  to select the next item in the popup menu
2. `<S-TAB>` to select the previous one
3. `<CR>` to confirm the selection of the current item in the popup menu
