### ISSUE TITLE
Breaks auto-pairs new line behaviour in Go files

### ISSUE THREAD

**Issue by achilleas-k** [roxma/SimpleAutoComplPop#8]
I have already reported this as [issue 149](https://github.com/jiangmiao/auto-pairs/issues/149) in auto-pairs, but after trying to find a minimum working example, I have narrowed it down to an interaction between auto-pairs and SACP.
### Actual behavior

When working with go files, after the first write, the new line behaviour of auto-pairs breaks.
The intended behaviour:

```
input: {|} (press <CR> at |)
output: {
    |
}
```

works fine at first. Once the file is saved, the next time the same input is given, the behaviour changes to:

```
input: {|} (press <CR> at |)
output: {
|}
```

To reproduce, simply install SACP, vim-go, and auto-pairs and test the behaviour described above. I am able to reproduce this by just having the three plugins enabled and no other settings in vimrc or any other ftplugin file.

Disabling gofmt on write in works around the issue. I have no idea how the three interact and which plugin is responsible for the issue.

**Comment by roxma** [comment]
Hi, It's  SACP's unnecessary `inoremap <CR>` key that conflicts with auto-pairs. I've remove the mapping. 

Update SACP to the latest version and try it.

**Comment by achilleas-k** [comment]
Wonderful! Works perfectly. Thanks for the quick fix.
