### ISSUE TITLE
[Enhancement] Scroll through up and down list with `C-j` and `C-k`

### ISSUE THREAD

**Issue by leighmcculloch** [roxma/SimpleAutoComplPop#9]
What
===
Scroll through up and down list with `C-j` and `C-k`.

Why
===
The only way to scroll is to by using the arrow keys, which requires taking hands off the main typing keys and is not ergonomic. Other vim plugins like [kien/ctrlp.vim](https://github.com/kien/ctrlp.vim) support scrolling through lists with `C-j` and `C-k` as well.

**Comment by leighmcculloch** [comment]
I'm up for doing the work to add this, but I'm a little lost on where to start. I can't see an entry point that registers for `<down>` and `<up>` to add in registration of `<c-j>` and `<c-k>`.

**Comment by roxma** [comment]
Hi, Vim has built-in key bindings `<C-n>`  and `<C-p>` for selecting popup menu. This may be what you want.

**Comment by leighmcculloch** [comment]
Ah right. Thanks @roxma. I found an example on [StackOverflow](http://stackoverflow.com/questions/21900031/vim-style-keys-to-navigate-up-and-down-in-omnicomplete-box#) of how to map `C-j/k` to `C-n/p` in insert mode.

```
inoremap <expr> <c-j> ("\<C-n>")
inoremap <expr> <c-k> ("\<C-p>")
```

**Comment by roxma** [comment]
Try this, pumvisible checks for the visible stat of the popup menu. On my computer, vim can't distinguish between `<c-j>` and `<Enter>` key.

```vim
inoremap <expr>   <c-j>  (pumvisible()?"\<C-n>":"\<c-j>")
```

**Comment by leighmcculloch** [comment]
Thanks! I've switched to using that.
